import argparse
import time
import json
from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.ml.feature import VectorAssembler, Imputer
from pyspark.ml.classification import RandomForestClassifier

def save_report_to_s3(spark, report_path, report_content):
    sc = spark.sparkContext
    URI = sc._gateway.jvm.java.net.URI
    Path = sc._gateway.jvm.org.apache.hadoop.fs.Path
    FileSystem = sc._gateway.jvm.org.apache.hadoop.fs.FileSystem
    
    fs = FileSystem.get(URI(report_path), sc._jsc.hadoopConfiguration())
    out = fs.create(Path(report_path), True)
    out.write(bytearray(report_content, "utf-8"))
    out.close()

def main():
    parser = argparse.ArgumentParser(description="Intermediate to Diamond ML Feature Selection")
    parser.add_argument("--intermediate-path", required=True, help="S3 path to the Intermediate parquet generated by dbt")
    parser.add_argument("--report-path", required=True, help="S3 path for the ML report")
    parser.add_argument("--json-path", required=True, help="S3 path for the ML JSON features")
    parser.add_argument("--target-col", default="is_default", help="Name of the target column")
    args = parser.parse_args()

    spark = SparkSession.builder \
        .appName(f"IntermediateToDiamond_ML") \
        .getOrCreate()

    # AWS Config
    spark.sparkContext._jsc.hadoopConfiguration().set("fs.s3a.aws.credentials.provider", "com.amazonaws.auth.DefaultAWSCredentialsProviderChain")
    spark.sparkContext._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "s3.amazonaws.com")

    start_time = time.time()
    
    # 1. Load Gold Data (The Fat Table from dbt)
    print(f"Leyendo Intermediate: {args.intermediate_path}")
    df = spark.read.parquet(args.intermediate_path)

    if args.target_col not in df.columns:
        print(f"ERROR: La tabla no tiene la columna target '{args.target_col}'.")
        spark.stop()
        return

    # Filter out null targets
    df = df.filter(col(args.target_col).isNotNull())
    
    # 2. Select numeric columns for ML
    numeric_types = ["integer", "long", "double", "float"]
    numeric_cols = [f.name for f in df.schema.fields if f.dataType.typeName() in numeric_types and f.name != args.target_col]
    
    # 3. Handle Nulls in features using Imputer (Random Forest in MLlib needs no nulls)
    imputed_cols = [c + "_imputed" for c in numeric_cols]
    imputer = Imputer(inputCols=numeric_cols, outputCols=imputed_cols).setStrategy("median")
    df_imputed = imputer.fit(df).transform(df)

    # 4. Assemble Features
    assembler = VectorAssembler(inputCols=imputed_cols, outputCol="features", handleInvalid="skip")
    df_assembled = assembler.transform(df_imputed)

    # 5. Train Random Forest with up to 1,000,000 rows
    total_rows = df_assembled.count()
    fraction = 1.0 if total_rows <= 1000000 else 1000000.0 / total_rows
    df_sample = df_assembled.sample(withReplacement=False, fraction=fraction, seed=42)

    print(f"Entrenando Random Forest con {int(total_rows * fraction)} filas para Feature Importance...")
    rf = RandomForestClassifier(featuresCol="features", labelCol=args.target_col, numTrees=50, maxDepth=5)
    rf_model = rf.fit(df_sample)

    # 6. Extract Feature Importance
    importances = rf_model.featureImportances.toArray()
    feature_imp = [(numeric_cols[i], float(importances[i])) for i in range(len(numeric_cols))]
    feature_imp.sort(key=lambda x: x[1], reverse=True)

    # Top 20 features + target + ID (assuming anything with 'id' is identifier)
    top_n = 20
    top_features = [f[0] for f in feature_imp[:top_n] if f[1] > 0.0]
    
    id_cols = [c for c in df.columns if 'id' in c.lower()]
    final_cols = list(set(id_cols + top_features + [args.target_col]))
    
    duration_sec = int(time.time() - start_time)

    # 7. Markdown Report
    report = f"# Reporte de Feature Selection\n\n"
    report += f"- **Tiempo de Entrenamiento/Procesamiento:** {duration_sec} segundos\n"
    report += f"- **Total de Filas Originales:** {total_rows}\n"
    report += f"- **Filas Usadas en Entrenamiento (Muestra 1M):** {int(total_rows * fraction)}\n"
    report += f"- **Columnas Finales Retenidas:** {len(final_cols)}\n\n"
    
    report += "## Top 20 Variables por Importancia (Random Forest)\n"
    report += "| Variable | Importancia (Gini) |\n"
    report += "|---|---|\n"
    for var, imp in feature_imp[:top_n]:
        if imp > 0:
            report += f"| `{var}` | {imp:.4f} |\n"
            
    report += "\n> **Instrucción para dbt:** Crea el modelo final en dbt (`diamond_risk_features.sql`) seleccionando estas variables exactas. Descarta el resto.\n"

    print(f"Guardando reporte en: {args.report_path}")
    save_report_to_s3(spark, args.report_path, report)
    
    # 8. JSON Report (Para MLOps y dbt)
    json_content = json.dumps({
        "target_column": args.target_col,
        "top_features": top_features,
        "feature_importances": {var: imp for var, imp in feature_imp[:top_n] if imp > 0}
    }, indent=4)
    
    print(f"Guardando JSON de variables en: {args.json_path}")
    save_report_to_s3(spark, args.json_path, json_content)
    
    print("Proceso ML completado exitosamente.")
    spark.stop()

if __name__ == "__main__":
    main()
