services:
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    user: root
    network_mode: host
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      --webui-port 8083
      --memory 1024M
      --cores 2
      spark://25.0.2.90:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOCAL_IP=11.0.2.107
      - SPARK_PUBLIC_DNS=11.0.2.107
    volumes:
      - /home/ubuntu/data-platform/spark-apps:/opt/spark-apps
    restart: unless-stopped
